### ISSUE TITLE
[Bug] E-Mail Alerting does not work.

### ISSUE THREAD

**Issue by 4920441** [DeineAgenturUG/greenbone-gvm-openvas-for-docker#2]
**Describe the bug**

When I configure an e-mail alert under Configuration/Alerts and attach the alert to a task, no e-Mail is sent, when the task is completed.

postfix seems to be configured and is running - but without loggin capabilities.

**Comment by Dexus** [comment]
join the running container via `docker exec .... bash` and look in /var/log/mail.* files to get your errors.
Postfix has no foreground mode so it can't log via supervisor.

**Comment by 4920441** [comment]
Hi, there are no logfiles, whatsoever.
Maybe because config has an empty logfile config.... that would be another config bug -)
