### ISSUE TITLE
Need help on Distributed setup GVM, OpenVas, GSA, Postgresql, GVM API

### ISSUE THREAD

**Issue by harshalgithub** [DeineAgenturUG/greenbone-gvm-openvas-for-docker#25]
Hi @Dexus ,

I was going through different repos present here, I am looking for Distributed setup of Openvas, GVM, GSA, Postgres, GVM API with remote Scanner Supported approach. 

I need common postgres database which would be used by remote scanners, so after finishing the scan, remotescanner can be shutdown/disposed but reports,logs should be stored on common postgres database, so with master GVM we can access logs,reports for future reference.

like I am looking for everything distributed with common database and with API support so we can access any component via API as well. 

Could you please let me know which Exact docker images Commands I need to follow with latest images. I gone through documentation but not seems very clear . If you give small step by step guide document example will be very helpful.

Thanks in advance.

**Comment by Dexus** [comment]
Hi @harshalgithub,

this setup will not be supported. We provide you an all-in-one image (gvm) which includes eveything you need. And also the remote scanner image (openvas-scanner).

We will not support an external database, the remote scanner (image: openvas-scanner) need to communicate with the master (image: gvm).

The setup of our gvm image, is to have the best performance without common problems, we have seen in the past.

You can access the postgresql database from external, if you need too. Also you can connect your python script to run the api calls.

You should only make sure you have your container on a reachable IP (best is to use one of this networkmodes: host, ipvlan, macvlan) for both gvm or openvas-scanner images.

Simple:
- run gvm image
- wait for the final initalisation -> check feed status in the WebUI or via API Request or docker exec
- run openvas-scanner image and follow the instuctions
- register the remote scanner in gvm container (`/opt/setup/scripts/add-scanner.sh`)
- restart openvas-scanner container

If you need professional help, you can use our paid support service. Please send us a mail to office (at) deineagentur.com.

Best Reagrds, Josef
