### ISSUE TITLE
Error on Report pages

### ISSUE THREAD

**Issue by tpaiii3** [DeineAgenturUG/greenbone-gvm-openvas-for-docker#34]
I found this error "An internal error occurred while getting resources list. The current list of resources is not available. Diagnostics: Failure to receive response from manager daemon."

![image](https://user-images.githubusercontent.com/85722230/169779614-4d082053-db89-4782-827e-32228d37c1d4.png)

Please help to suggest me.

**Comment by Dexus** [comment]
Please check the logs:

```
docker exec -ti gvm-container supervisorctl status
docker exec -ti gvm-container cat /var/log/gvm/*
docker exec -ti gvm-container cat /var/log/supervisord/*
```

**Comment by tpaiii3** [comment]
Hi, Dexus

![image](https://user-images.githubusercontent.com/85722230/169982645-a292d38b-9e2b-4ee7-8d32-58f4b2d9c7c3.png)

**Comment by Dexus** [comment]
How are your feed status? Administration->Feed Status

It looks for me like you interrupt the container while it was syncing. you should restart the container - then run (after feed status is not syncing anymore) the `gvmd --rebuild-gvmd-data=all` followed by a `--rebuild-scap`

Hope it help.

**Comment by tpaiii3** [comment]
It's not work.

![image](https://user-images.githubusercontent.com/85722230/170177111-e60d1116-bbe4-4954-8b57-9d69b91d8dbd.png)

![image](https://user-images.githubusercontent.com/85722230/170177235-b5d51edc-fc7d-4d5f-a661-f0ba61d4bca4.png)

more error in below.
![image](https://user-images.githubusercontent.com/85722230/170177307-9c2dfda3-92f0-4d1b-9d08-31c7d124bba2.png)

**Comment by Dexus** [comment]
can you please provide `docker inspect gvm99` ? I never had this issue before.

Did you update from an older version, if yes which one?

**Comment by Dexus** [comment]
Can't help here, if you not provide information's.

**Comment by tpaiii3** [comment]
Dexus, 

**Here's the result**


 sudo docker inspect gvm99
[
    {
        "Id": "7162f977530519747fef595a667279b1cc4293f8c47562aed966ca12d18aea94",
        "Created": "2022-05-24T14:32:25.439354766Z",
        "Path": "/opt/setup/scripts/entrypoint.sh",
        "Args": [
            "/usr/bin/supervisord",
            "-n",
            "-c",
            "/etc/supervisord.conf"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 115953,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2022-05-27T15:37:52.712046198Z",
            "FinishedAt": "2022-05-27T15:37:45.740050842Z"
        },
        "Image": "sha256:b7bab7d0e09d22e4514db0e2b0a0d12b5f94962a2b49c3ccc2c771493f222d9d",
        "ResolvConfPath": "/var/lib/docker/containers/7162f977530519747fef595a667279b1cc4293f8c47562aed966ca12d18aea94/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/7162f977530519747fef595a667279b1cc4293f8c47562aed966ca12d18aea94/hostname",
        "HostsPath": "/var/lib/docker/containers/7162f977530519747fef595a667279b1cc4293f8c47562aed966ca12d18aea94/hosts",
        "LogPath": "",
        "Name": "/gvm99",
        "RestartCount": 0,
        "Driver": "overlay2",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "journald",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "22/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "2224"
                    }
                ],
                "5432/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "5434"
                    }
                ],
                "9392/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "8086"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "docker-runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Name": "overlay2",
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/5dc58b458b230cdc7803e6cfca068fcc512ceabb534f74d140794fdb0e3105d2-init/diff:/var/lib/docker/overlay2/16a6152ac921f7fe2319ed2a3833f3543001c214e5934986267d1c6e2df70cd4/diff:/var/lib/docker/overlay2/10a2909508cdec2fd185a10bbe9c2da427cdddf2536c62563e932a496a83c5cf/diff:/var/lib/docker/overlay2/62f53717e9dc8f7700cccf0771c2f79974283699da6f9d8d79fd59288caf89dd/diff:/var/lib/docker/overlay2/dbd524fb0aa84d8ba240b83c5e314ae21c7f4b17849b86e2b9a262264c489d86/diff:/var/lib/docker/overlay2/20e3fcab4cd31f7a5b06e65a91230b033f54b06f631a13852d1e8c50982cc9bf/diff:/var/lib/docker/overlay2/0c7f8d6a7ef38381fc3421bbbee237f4cb3139b2a2598cddf3383ada7d1a4cd8/diff:/var/lib/docker/overlay2/c3058e5fbbbfc3887b3227407f2c0455ed8e4cbd4c9d9f20f6a61796e8178478/diff:/var/lib/docker/overlay2/e80699c14b1e67036139af1102d5dbc66f83fb2bdfdefcb93fff9f5f5f2ae267/diff:/var/lib/docker/overlay2/db730773ad06e9a819aede58ef0aa9fc33718c8de9a39d4b04b5adbefe385e82/diff:/var/lib/docker/overlay2/b9450633d2e311206dbf24c4b278bae7558a32ec956f84ba0406203e242f6cb2/diff:/var/lib/docker/overlay2/b33d655370b4c5ab2364ecf0bf150998caf9f8117eae460bcfd93d4ba1bf5b8b/diff",
                "MergedDir": "/var/lib/docker/overlay2/5dc58b458b230cdc7803e6cfca068fcc512ceabb534f74d140794fdb0e3105d2/merged",
                "UpperDir": "/var/lib/docker/overlay2/5dc58b458b230cdc7803e6cfca068fcc512ceabb534f74d140794fdb0e3105d2/diff",
                "WorkDir": "/var/lib/docker/overlay2/5dc58b458b230cdc7803e6cfca068fcc512ceabb534f74d140794fdb0e3105d2/work"
            }
        },
        "Mounts": [],
        "Config": {
            "Hostname": "7162f9775305",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "22/tcp": {},
                "5432/tcp": {},
                "9392/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "DB_PASSWORD=GVMP@ssw0rd",
                "PASSWORD=CatchingFire99",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "POSTGRESQL_VERSION=13",
                "GSAD_VERSION=21.4.4",
                "GSA_VERSION=21.4.4",
                "GVM_LIBS_VERSION=21.4.4",
                "GVMD_VERSION=21.4.5",
                "OPENVAS_SCANNER_VERSION=21.4.4",
                "OPENVAS_SMB_VERSION=21.4.0",
                "PYTHON_GVM_VERSION=21.11.0",
                "OSPD_OPENVAS_VERSION=21.4.4",
                "GVM_TOOLS_VERSION=21.10.0",
                "SYSTEM_DIST=debian",
                "SUPVISD=supervisorctl",
                "USERNAME=admin",
                "PASSWORD_FILE=none",
                "TIMEOUT=15",
                "DEBUG=N",
                "RELAYHOST=smtp",
                "SMTPPORT=25",
                "AUTO_SYNC=YES",
                "AUTO_SYNC_ON_START=YES",
                "HTTPS=true",
                "CERTIFICATE=none",
                "CERTIFICATE_KEY=none",
                "TZ=Etc/UTC",
                "SSHD=false",
                "DB_PASSWORD_FILE=none",
                "DEBIAN_FRONTEND=noninteractive",
                "LANG=en_US.UTF-8",
                "SETUP=0",
                "OPT_PDF=1",
                "LANGUAGE=en_US.UTF-8",
                "LC_ALL=en_US.UTF-8"
            ],
            "Cmd": [
                "/usr/bin/supervisord",
                "-n",
                "-c",
                "/etc/supervisord.conf"
            ],
            "ArgsEscaped": true,
            "Image": "deineagenturug/gvm:latest-data-full",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/opt/setup/scripts/entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "4a1249087bec5284c62a239a99398c4dfe95355fdd3b3d1cabf3d85422249b4b",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "22/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "2224"
                    }
                ],
                "5432/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "5434"
                    }
                ],
                "9392/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8086"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/4a1249087bec",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "43540ba21b06fa3bf039420480c2a172f261c45bba11c2d73a9c9a02fe4527f0",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "53968d67d5f19c9725674b12b67863ba60aba8f8ee8b8e7e297447bc179ca6be",
                    "EndpointID": "43540ba21b06fa3bf039420480c2a172f261c45bba11c2d73a9c9a02fe4527f0",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02"
                }
            }
        }
    }
]

**Comment by Dexus** [comment]
Hmm, I'm not sure what here is the problem. It can have todo with your security profiles or with your firewall (don't expect that here). Can you look what the `supervisorctl` command within your container showing?
