### ISSUE TITLE
WIKI: FAQ - SSL Certificate Instruction Typo

### ISSUE THREAD

**Issue by jerwah** [DeineAgenturUG/greenbone-gvm-openvas-for-docker#35]
[FAQ\Question 8 - How can I use my own SSL Certificate?](https://github.com/DeineAgenturUG/greenbone-gvm-openvas-for-docker/wiki/FAQ#question-8---how-can-i-use-my-own-ssl-certificate)

Solution #2 It States:
> CERTIFICATE=/secrets/ssl/MY_SSL_CERT.key

Should READ:
CERTIFICATE_KEY=/secrets/ssl/MY_SSL_CERT.key

**Comment by Dexus** [comment]
Thank you. It is fixed
